server:
  port: {MY_BACKEND_PORT}
spring:
  application:
    name: api-gateway
  profiles:
    active: {SPRING_PROFILE_ACTIVE}
  config:
    import: configserver:http://{MY_BACKEND_CONFIG_SERVER_IP}:{MY_BACKEND_CONFIG_SERVER_PORT}

