// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.6.1
// source: nginx.proto

package nginx

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NginxHandler_Restart_FullMethodName = "/NginxHandler/Restart"
)

// NginxHandlerClient is the client API for NginxHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NginxHandlerClient interface {
	Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*RestartResponse, error)
}

type nginxHandlerClient struct {
	cc grpc.ClientConnInterface
}

func NewNginxHandlerClient(cc grpc.ClientConnInterface) NginxHandlerClient {
	return &nginxHandlerClient{cc}
}

func (c *nginxHandlerClient) Restart(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*RestartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestartResponse)
	err := c.cc.Invoke(ctx, NginxHandler_Restart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NginxHandlerServer is the server API for NginxHandler service.
// All implementations must embed UnimplementedNginxHandlerServer
// for forward compatibility.
type NginxHandlerServer interface {
	Restart(context.Context, *RestartRequest) (*RestartResponse, error)
	mustEmbedUnimplementedNginxHandlerServer()
}

// UnimplementedNginxHandlerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNginxHandlerServer struct{}

func (UnimplementedNginxHandlerServer) Restart(context.Context, *RestartRequest) (*RestartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedNginxHandlerServer) mustEmbedUnimplementedNginxHandlerServer() {}
func (UnimplementedNginxHandlerServer) testEmbeddedByValue()                      {}

// UnsafeNginxHandlerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NginxHandlerServer will
// result in compilation errors.
type UnsafeNginxHandlerServer interface {
	mustEmbedUnimplementedNginxHandlerServer()
}

func RegisterNginxHandlerServer(s grpc.ServiceRegistrar, srv NginxHandlerServer) {
	// If the following call pancis, it indicates UnimplementedNginxHandlerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NginxHandler_ServiceDesc, srv)
}

func _NginxHandler_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NginxHandlerServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NginxHandler_Restart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NginxHandlerServer).Restart(ctx, req.(*RestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NginxHandler_ServiceDesc is the grpc.ServiceDesc for NginxHandler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NginxHandler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NginxHandler",
	HandlerType: (*NginxHandlerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Restart",
			Handler:    _NginxHandler_Restart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nginx.proto",
}
